#version 460
#extension GL_EXT_ray_query : require
layout(local_size_x = 1) in;
layout(set = 0, binding = 0) uniform accelerationStructureEXT scene;
layout(set = 0, binding = 1, std430) buffer Results { uint result[]; };
void main() {
    uint i = gl_GlobalInvocationID.x;
    rayQueryEXT ray;
    rayQueryInitializeEXT(ray, scene, gl_RayFlagsOpaqueEXT, 255,
        vec3((i & 1) == 0 ? 0.0 : 2.0, 0.0, 1.0), 0.001, vec3(0, 0, -1), 10.0);
    while (rayQueryProceedEXT(ray)) {}
    result[i] = rayQueryGetIntersectionTypeEXT(ray, true) == gl_RayQueryCommittedIntersectionTriangleEXT ? 11 : 22;
}
