#version 460
#extension GL_EXT_ray_tracing : require
layout(set = 0, binding = 0) uniform accelerationStructureEXT scene;
layout(set = 0, binding = 1, std430) buffer Results { uint result[]; };
layout(location = 0) rayPayloadEXT uint value;
void main() {
    uint i = gl_LaunchIDEXT.x;
    vec2 pixel = vec2(i % 128, i / 128);
    vec2 position = (pixel + 0.5) / vec2(128, 96) * 2.0 - 1.0;
    value = 0;
    traceRayEXT(scene, gl_RayFlagsOpaqueEXT, 255, 0, 0, 0,
        vec3(position, 1), 0.001, vec3(0, 0, -1), 10.0, 0);
    result[i] = value;
}
