#version 460
#extension GL_EXT_ray_tracing : require
layout(set = 0, binding = 0) uniform accelerationStructureEXT scene;
layout(set = 0, binding = 1, std430) buffer Results { uint result[]; };
layout(location = 0) rayPayloadEXT uint value;
void main() {
    uint i = gl_LaunchIDEXT.x;
    value = 0;
    traceRayEXT(scene, gl_RayFlagsOpaqueEXT, 255, 0, 0, 0,
        vec3((i & 1) == 0 ? 0.0 : 2.0, 0.0, 1.0), 0.001, vec3(0, 0, -1), 10.0, 0);
    result[i] = value;
}
